version: '3'
services:
  app:
    image: golang:1.11.1
    volumes:
      - ./:/go/src/github.com/yutify/gengo-api/
    working_dir: /go/src/github.com/yutify/gegno-api/
    environment:
      - GO111MODULE=on
      - CGO_ENABLED=0
    command: |
      bash -c " \
      echo '=== Start ==='"
    ports:
      - 8080:8080
    depends_on:
      - mysql

  mysql:
    image: mysql:5.7
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=gengodb
      - MYSQL_USER=user
      - MYSQL_PASSWORD=pass
      - TZ=Asia/Tokyo
    ports:
      - 3306:3306