[server]
  port = ":8080"

[dbm]
  host = "mysql"
  port = ":3306"
  user = "user"
  password = "pass"
  dbname = "gengodb"

[dbs]
  host = "mysql"
  port = ":3306"
  user = "user"
  password = "pass"
  dbname = "gengodb"

